export const uiText = {
  en: {
    appLabel: "French practice",
    title: "French Garden",
    languageLabel: "App language",
    levelPill: "Beginner friendly",
    heroTitle: "Tiny French steps, every day.",
    heroCopy:
      "Learn useful words, simple phrases, listening, and pronunciation in short playful rounds.",
    scoreLabel: "Score",
    streakLabel: "Good answers",
    learnedLabel: "Practiced",
    reviewLabel: "To review",
    levelFilterLabel: "Level",
    categoryFilterLabel: "Category",
    reviewOnlyLabel: "Review only",
    progressEyebrow: "Progress",
    progressTitle: "Practice by category",
    cardsTab: "Cards",
    quizTab: "Quiz",
    matchTab: "Match",
    phrasesTab: "Phrases",
    cardsEyebrow: "Vocabulary",
    cardsTitle: "Tap, listen, remember",
    newCardTitle: "New card",
    previousButton: "Previous",
    nextButton: "Next",
    listenButton: "Listen",
    knowButton: "I know it",
    reviewButton: "Review later",
    quizEyebrow: "Quick quiz",
    quizTitle: "Choose the meaning",
    quizPrompt: "What does this mean?",
    matchEyebrow: "Memory match",
    matchTitle: "Pair French with meaning",
    resetButton: "Reset",
    phrasesEyebrow: "Useful phrases",
    phrasesTitle: "Complete the sentence",
    listenPhraseButton: "Hear phrase",
    correct: "Nice! That is correct.",
    wrong: "Almost. Try this one again.",
    matched: "Matched!",
    allLevels: "All levels",
    allCategories: "All categories",
    level: "Level",
    level1: "Level 1",
    level2: "Level 2",
    level3: "Level 3",
    cardAvailable: "word available",
    cardsAvailable: "words available",
    quizWordAvailable: "quiz word",
    quizAvailable: "quiz words",
    matchWordAvailable: "match word",
    matchAvailable: "match words",
    phraseAvailable: "phrase available",
    phrasesAvailable: "phrases available",
    emptyReview: "Nothing to review yet. Mark words for review or miss a quiz answer.",
  },
  be: {
    appLabel: "Практыка французскай",
    title: "Французскі сад",
    languageLabel: "Мова праграмы",
    levelPill: "Для пачаткоўцаў",
    heroTitle: "Маленькія крокі па-французску кожны дзень.",
    heroCopy:
      "Вучы карысныя словы, простыя фразы, слуханне і вымаўленне ў кароткіх гульнях.",
    scoreLabel: "Балы",
    streakLabel: "Добрыя адказы",
    learnedLabel: "Практыка",
    reviewLabel: "На паўтор",
    levelFilterLabel: "Узровень",
    categoryFilterLabel: "Катэгорыя",
    reviewOnlyLabel: "Толькі паўтор",
    progressEyebrow: "Прагрэс",
    progressTitle: "Практыка па катэгорыях",
    cardsTab: "Карткі",
    quizTab: "Тэст",
    matchTab: "Пары",
    phrasesTab: "Фразы",
    cardsEyebrow: "Слоўнік",
    cardsTitle: "Націсні, паслухай, запомні",
    newCardTitle: "Новая картка",
    previousButton: "Назад",
    nextButton: "Далей",
    listenButton: "Слухаць",
    knowButton: "Я ведаю",
    reviewButton: "Паўтарыць пазней",
    quizEyebrow: "Хуткі тэст",
    quizTitle: "Абяры значэнне",
    quizPrompt: "Што гэта значыць?",
    matchEyebrow: "Гульня на памяць",
    matchTitle: "Знайдзі пару",
    resetButton: "Скінуць",
    phrasesEyebrow: "Карысныя фразы",
    phrasesTitle: "Дапоўні сказ",
    listenPhraseButton: "Паслухаць фразу",
    correct: "Выдатна! Правільна.",
    wrong: "Амаль. Паспрабуй яшчэ раз.",
    matched: "Пара знойдзена!",
    allLevels: "Усе ўзроўні",
    allCategories: "Усе катэгорыі",
    level: "Узровень",
    level1: "Узровень 1",
    level2: "Узровень 2",
    level3: "Узровень 3",
    cardAvailable: "слова даступна",
    cardsAvailable: "слоў даступна",
    quizWordAvailable: "слова ў тэсце",
    quizAvailable: "слоў у тэсце",
    matchWordAvailable: "слова для пар",
    matchAvailable: "слоў для пар",
    phraseAvailable: "фраза даступна",
    phrasesAvailable: "фраз даступна",
    emptyReview: "Пакуль няма слоў на паўтор. Адзнач словы або памыліся ў тэсце.",
  },
};

export const vocabulary = [
  { id: "hello", category: "Greetings", french: "bonjour", translations: { en: "hello", be: "прывітанне" } },
  { id: "good-evening", category: "Greetings", french: "bonsoir", translations: { en: "good evening", be: "добры вечар" } },
  { id: "goodbye", category: "Greetings", french: "au revoir", translations: { en: "goodbye", be: "да пабачэння" } },
  { id: "see-you-soon", category: "Greetings", french: "à bientôt", translations: { en: "see you soon", be: "да хуткай сустрэчы" } },
  { id: "thanks", category: "Politeness", french: "merci", translations: { en: "thank you", be: "дзякуй" } },
  { id: "please", category: "Politeness", french: "s’il te plaît", translations: { en: "please", be: "калі ласка" } },
  { id: "sorry", category: "Politeness", french: "pardon", translations: { en: "sorry", be: "прабач" } },
  { id: "yes", category: "Basics", french: "oui", translations: { en: "yes", be: "так" } },
  { id: "no", category: "Basics", french: "non", translations: { en: "no", be: "не" } },
  { id: "maybe", category: "Basics", french: "peut-être", translations: { en: "maybe", be: "магчыма" } },
  { id: "here", category: "Basics", french: "ici", translations: { en: "here", be: "тут" } },
  { id: "there", category: "Basics", french: "là-bas", translations: { en: "over there", be: "там" } },
  { id: "water", category: "Food", french: "de l’eau", translations: { en: "water", be: "вада" } },
  { id: "bread", category: "Food", french: "du pain", translations: { en: "bread", be: "хлеб" } },
  { id: "coffee", category: "Food", french: "un café", translations: { en: "a coffee", be: "кава" } },
  { id: "tea", category: "Food", french: "du thé", translations: { en: "tea", be: "гарбата" } },
  { id: "milk", category: "Food", french: "du lait", translations: { en: "milk", be: "малако" } },
  { id: "sugar", category: "Food", french: "du sucre", translations: { en: "sugar", be: "цукар" } },
  { id: "salt", category: "Food", french: "du sel", translations: { en: "salt", be: "соль" } },
  { id: "apple", category: "Food", french: "une pomme", translations: { en: "an apple", be: "яблык" } },
  { id: "banana", category: "Food", french: "une banane", translations: { en: "a banana", be: "банан" } },
  { id: "cheese", category: "Food", french: "du fromage", translations: { en: "cheese", be: "сыр" } },
  { id: "rice", category: "Food", french: "du riz", translations: { en: "rice", be: "рыс" } },
  { id: "soup", category: "Food", french: "de la soupe", translations: { en: "soup", be: "суп" } },
  { id: "chicken", category: "Food", french: "du poulet", translations: { en: "chicken", be: "курыца" } },
  { id: "fish", category: "Food", french: "du poisson", translations: { en: "fish", be: "рыба" } },
  { id: "house", category: "Home", french: "la maison", translations: { en: "the house", be: "дом" } },
  { id: "room", category: "Home", french: "la chambre", translations: { en: "the bedroom", be: "спальня" } },
  { id: "kitchen", category: "Home", french: "la cuisine", translations: { en: "the kitchen", be: "кухня" } },
  { id: "bathroom", category: "Home", french: "la salle de bain", translations: { en: "the bathroom", be: "ванны пакой" } },
  { id: "door", category: "Home", french: "la porte", translations: { en: "the door", be: "дзверы" } },
  { id: "window", category: "Home", french: "la fenêtre", translations: { en: "the window", be: "акно" } },
  { id: "table", category: "Home", french: "la table", translations: { en: "the table", be: "стол" } },
  { id: "chair", category: "Home", french: "la chaise", translations: { en: "the chair", be: "крэсла" } },
  { id: "bed", category: "Home", french: "le lit", translations: { en: "the bed", be: "ложак" } },
  { id: "key", category: "Home", french: "la clé", translations: { en: "the key", be: "ключ" } },
  { id: "phone", category: "Daily life", french: "le téléphone", translations: { en: "the phone", be: "тэлефон" } },
  { id: "bag", category: "Daily life", french: "le sac", translations: { en: "the bag", be: "сумка" } },
  { id: "book", category: "Daily life", french: "le livre", translations: { en: "the book", be: "кніга" } },
  { id: "pen", category: "Daily life", french: "le stylo", translations: { en: "the pen", be: "ручка" } },
  { id: "money", category: "Daily life", french: "l’argent", translations: { en: "money", be: "грошы" } },
  { id: "ticket", category: "Daily life", french: "le ticket", translations: { en: "the ticket", be: "білет" } },
  { id: "today", category: "Time", french: "aujourd’hui", translations: { en: "today", be: "сёння" } },
  { id: "tomorrow", category: "Time", french: "demain", translations: { en: "tomorrow", be: "заўтра" } },
  { id: "yesterday", category: "Time", french: "hier", translations: { en: "yesterday", be: "учора" } },
  { id: "morning", category: "Time", french: "le matin", translations: { en: "the morning", be: "раніца" } },
  { id: "evening", category: "Time", french: "le soir", translations: { en: "the evening", be: "вечар" } },
  { id: "now", category: "Time", french: "maintenant", translations: { en: "now", be: "зараз" } },
  { id: "later", category: "Time", french: "plus tard", translations: { en: "later", be: "пазней" } },
  { id: "monday", category: "Time", french: "lundi", translations: { en: "Monday", be: "панядзелак" } },
  { id: "friday", category: "Time", french: "vendredi", translations: { en: "Friday", be: "пятніца" } },
  { id: "happy", category: "Feelings", french: "content", translations: { en: "happy", be: "рады" } },
  { id: "tired", category: "Feelings", french: "fatiguée", translations: { en: "tired", be: "стомленая" } },
  { id: "hungry", category: "Feelings", french: "j’ai faim", translations: { en: "I am hungry", be: "я галодная" } },
  { id: "thirsty", category: "Feelings", french: "j’ai soif", translations: { en: "I am thirsty", be: "я хачу піць" } },
  { id: "cold", category: "Feelings", french: "j’ai froid", translations: { en: "I am cold", be: "мне холадна" } },
  { id: "hot", category: "Feelings", french: "j’ai chaud", translations: { en: "I am hot", be: "мне горача" } },
  { id: "sick", category: "Health", french: "malade", translations: { en: "sick", be: "хворая" } },
  { id: "head", category: "Health", french: "la tête", translations: { en: "the head", be: "галава" } },
  { id: "stomach", category: "Health", french: "le ventre", translations: { en: "the stomach", be: "жывот" } },
  { id: "medicine", category: "Health", french: "le médicament", translations: { en: "the medicine", be: "лекі" } },
  { id: "doctor", category: "Health", french: "le médecin", translations: { en: "the doctor", be: "доктар" } },
  { id: "street", category: "Places", french: "la rue", translations: { en: "the street", be: "вуліца" } },
  { id: "shop", category: "Places", french: "le magasin", translations: { en: "the shop", be: "крама" } },
  { id: "restaurant", category: "Places", french: "le restaurant", translations: { en: "the restaurant", be: "рэстаран" } },
  { id: "station", category: "Places", french: "la gare", translations: { en: "the train station", be: "вакзал" } },
  { id: "pharmacy", category: "Places", french: "la pharmacie", translations: { en: "the pharmacy", be: "аптэка" } },
  { id: "park", category: "Places", french: "le parc", translations: { en: "the park", be: "парк" } },
  { id: "car", category: "Transport", french: "la voiture", translations: { en: "the car", be: "машына" } },
  { id: "train", category: "Transport", french: "le train", translations: { en: "the train", be: "цягнік" } },
  { id: "bus", category: "Transport", french: "le bus", translations: { en: "the bus", be: "аўтобус" } },
  { id: "metro", category: "Transport", french: "le métro", translations: { en: "the metro", be: "метро" } },
  { id: "left", category: "Directions", french: "à gauche", translations: { en: "to the left", be: "налева" } },
  { id: "right", category: "Directions", french: "à droite", translations: { en: "to the right", be: "направа" } },
  { id: "straight", category: "Directions", french: "tout droit", translations: { en: "straight ahead", be: "прама" } },
  { id: "near", category: "Directions", french: "près de", translations: { en: "near", be: "каля" } },
  { id: "far", category: "Directions", french: "loin de", translations: { en: "far from", be: "далёка ад" } },
  { id: "small", category: "Descriptions", french: "petit", translations: { en: "small", be: "маленькі" } },
  { id: "big", category: "Descriptions", french: "grand", translations: { en: "big", be: "вялікі" } },
  { id: "good", category: "Descriptions", french: "bon", translations: { en: "good", be: "добры" } },
  { id: "beautiful", category: "Descriptions", french: "beau", translations: { en: "beautiful", be: "прыгожы" } },
  { id: "expensive", category: "Shopping", french: "cher", translations: { en: "expensive", be: "дарагі" } },
  { id: "cheap", category: "Shopping", french: "pas cher", translations: { en: "cheap", be: "танны" } },
  { id: "receipt", category: "Shopping", french: "le ticket de caisse", translations: { en: "the receipt", be: "чэк" } },
];

export const phrases = [
  {
    id: "how-are-you",
    text: "Comment ça va ?",
    missing: "ça va",
    translations: {
      en: "How are you?",
      be: "Як справы?",
    },
    options: ["ça va", "maison", "demain"],
  },
  {
    id: "i-want-water",
    text: "Je voudrais de l’eau.",
    missing: "de l’eau",
    translations: {
      en: "I would like some water.",
      be: "Я хацела б вады.",
    },
    options: ["du pain", "de l’eau", "merci"],
  },
  {
    id: "where-is-phone",
    text: "Où est mon téléphone ?",
    missing: "téléphone",
    translations: {
      en: "Where is my phone?",
      be: "Дзе мой тэлефон?",
    },
    options: ["café", "téléphone", "maison"],
  },
  {
    id: "i-am-tired",
    text: "Je suis fatiguée.",
    missing: "fatiguée",
    translations: {
      en: "I am tired.",
      be: "Я стомленая.",
    },
    options: ["content", "bonjour", "fatiguée"],
  },
  {
    id: "see-you-tomorrow",
    text: "À demain !",
    missing: "demain",
    translations: {
      en: "See you tomorrow!",
      be: "Да заўтра!",
    },
    options: ["demain", "pain", "eau"],
  },
  {
    id: "good-morning",
    text: "Bonjour, ça va ?",
    missing: "Bonjour",
    translations: { en: "Hello, how are you?", be: "Прывітанне, як справы?" },
    options: ["Bonjour", "Merci", "Demain"],
  },
  {
    id: "thank-you-very-much",
    text: "Merci beaucoup.",
    missing: "beaucoup",
    translations: { en: "Thank you very much.", be: "Вялікі дзякуй." },
    options: ["beaucoup", "gauche", "maison"],
  },
  {
    id: "i-do-not-understand",
    text: "Je ne comprends pas.",
    missing: "comprends",
    translations: { en: "I do not understand.", be: "Я не разумею." },
    options: ["comprends", "voudrais", "mange"],
  },
  {
    id: "repeat-please",
    text: "Tu peux répéter, s’il te plaît ?",
    missing: "répéter",
    translations: { en: "Can you repeat, please?", be: "Можаш паўтарыць, калі ласка?" },
    options: ["répéter", "acheter", "dormir"],
  },
  {
    id: "speak-slowly",
    text: "Parle lentement, s’il te plaît.",
    missing: "lentement",
    translations: { en: "Speak slowly, please.", be: "Гавары павольна, калі ласка." },
    options: ["lentement", "demain", "chaud"],
  },
  {
    id: "my-name-is",
    text: "Je m’appelle Anna.",
    missing: "m’appelle",
    translations: { en: "My name is Anna.", be: "Мяне завуць Анна." },
    options: ["m’appelle", "voudrais", "cherche"],
  },
  {
    id: "nice-to-meet-you",
    text: "Enchantée.",
    missing: "Enchantée",
    translations: { en: "Nice to meet you.", be: "Прыемна пазнаёміцца." },
    options: ["Enchantée", "Fatiguée", "Gauche"],
  },
  {
    id: "i-live-here",
    text: "J’habite ici.",
    missing: "ici",
    translations: { en: "I live here.", be: "Я жыву тут." },
    options: ["ici", "pain", "train"],
  },
  {
    id: "i-am-belarusian",
    text: "Je suis biélorusse.",
    missing: "biélorusse",
    translations: { en: "I am Belarusian.", be: "Я беларуска." },
    options: ["biélorusse", "fatiguée", "droite"],
  },
  {
    id: "i-speak-a-little",
    text: "Je parle un peu français.",
    missing: "un peu",
    translations: { en: "I speak a little French.", be: "Я крыху гавару па-французску." },
    options: ["un peu", "beaucoup", "tout droit"],
  },
  {
    id: "i-want-coffee",
    text: "Je voudrais un café.",
    missing: "café",
    translations: { en: "I would like a coffee.", be: "Я хацела б каву." },
    options: ["café", "clé", "gare"],
  },
  {
    id: "i-want-tea",
    text: "Je voudrais du thé.",
    missing: "thé",
    translations: { en: "I would like tea.", be: "Я хацела б гарбаты." },
    options: ["thé", "lit", "sac"],
  },
  {
    id: "without-sugar",
    text: "Sans sucre, s’il vous plaît.",
    missing: "sucre",
    translations: { en: "Without sugar, please.", be: "Без цукру, калі ласка." },
    options: ["sucre", "sel", "ticket"],
  },
  {
    id: "with-milk",
    text: "Avec du lait.",
    missing: "lait",
    translations: { en: "With milk.", be: "З малаком." },
    options: ["lait", "riz", "rue"],
  },
  {
    id: "i-am-hungry",
    text: "J’ai faim.",
    missing: "faim",
    translations: { en: "I am hungry.", be: "Я галодная." },
    options: ["faim", "froid", "chaud"],
  },
  {
    id: "i-am-thirsty",
    text: "J’ai soif.",
    missing: "soif",
    translations: { en: "I am thirsty.", be: "Я хачу піць." },
    options: ["soif", "soupe", "soir"],
  },
  {
    id: "where-is-bathroom",
    text: "Où sont les toilettes ?",
    missing: "toilettes",
    translations: { en: "Where are the toilets?", be: "Дзе туалет?" },
    options: ["toilettes", "fenêtres", "pommes"],
  },
  {
    id: "where-is-station",
    text: "Où est la gare ?",
    missing: "gare",
    translations: { en: "Where is the train station?", be: "Дзе вакзал?" },
    options: ["gare", "chaise", "banane"],
  },
  {
    id: "where-is-shop",
    text: "Où est le magasin ?",
    missing: "magasin",
    translations: { en: "Where is the shop?", be: "Дзе крама?" },
    options: ["magasin", "médecin", "poisson"],
  },
  {
    id: "turn-left",
    text: "Tourne à gauche.",
    missing: "gauche",
    translations: { en: "Turn left.", be: "Павярні налева." },
    options: ["gauche", "droite", "ici"],
  },
  {
    id: "turn-right",
    text: "Tourne à droite.",
    missing: "droite",
    translations: { en: "Turn right.", be: "Павярні направа." },
    options: ["droite", "gauche", "demain"],
  },
  {
    id: "go-straight",
    text: "Va tout droit.",
    missing: "droit",
    translations: { en: "Go straight ahead.", be: "Ідзі прама." },
    options: ["droit", "soir", "sac"],
  },
  {
    id: "how-much",
    text: "Ça coûte combien ?",
    missing: "combien",
    translations: { en: "How much does it cost?", be: "Колькі гэта каштуе?" },
    options: ["combien", "comment", "bonjour"],
  },
  {
    id: "too-expensive",
    text: "C’est trop cher.",
    missing: "cher",
    translations: { en: "It is too expensive.", be: "Гэта занадта дорага." },
    options: ["cher", "froid", "petit"],
  },
  {
    id: "i-pay-card",
    text: "Je paie par carte.",
    missing: "carte",
    translations: { en: "I pay by card.", be: "Я плачу картай." },
    options: ["carte", "clé", "pomme"],
  },
  {
    id: "receipt-please",
    text: "Le ticket, s’il vous plaît.",
    missing: "ticket",
    translations: { en: "The receipt, please.", be: "Чэк, калі ласка." },
    options: ["ticket", "train", "thé"],
  },
  {
    id: "i-am-cold",
    text: "J’ai froid.",
    missing: "froid",
    translations: { en: "I am cold.", be: "Мне холадна." },
    options: ["froid", "chaud", "faim"],
  },
  {
    id: "i-am-hot",
    text: "J’ai chaud.",
    missing: "chaud",
    translations: { en: "I am hot.", be: "Мне горача." },
    options: ["chaud", "froid", "soif"],
  },
  {
    id: "my-head-hurts",
    text: "J’ai mal à la tête.",
    missing: "tête",
    translations: { en: "My head hurts.", be: "У мяне баліць галава." },
    options: ["tête", "porte", "riz"],
  },
  {
    id: "i-need-doctor",
    text: "J’ai besoin d’un médecin.",
    missing: "médecin",
    translations: { en: "I need a doctor.", be: "Мне патрэбен доктар." },
    options: ["médecin", "magasin", "métro"],
  },
  {
    id: "i-need-medicine",
    text: "J’ai besoin d’un médicament.",
    missing: "médicament",
    translations: { en: "I need medicine.", be: "Мне патрэбныя лекі." },
    options: ["médicament", "restaurant", "fromage"],
  },
  {
    id: "i-am-lost",
    text: "Je suis perdue.",
    missing: "perdue",
    translations: { en: "I am lost.", be: "Я заблудзілася." },
    options: ["perdue", "content", "beau"],
  },
  {
    id: "help-me",
    text: "Aide-moi, s’il te plaît.",
    missing: "Aide-moi",
    translations: { en: "Help me, please.", be: "Дапамажы мне, калі ласка." },
    options: ["Aide-moi", "Bonjour", "À demain"],
  },
  {
    id: "call-me",
    text: "Appelle-moi.",
    missing: "Appelle-moi",
    translations: { en: "Call me.", be: "Патэлефануй мне." },
    options: ["Appelle-moi", "Tourne", "Mange"],
  },
  {
    id: "i-am-coming",
    text: "J’arrive.",
    missing: "arrive",
    translations: { en: "I am coming.", be: "Я іду." },
    options: ["arrive", "habite", "coûte"],
  },
  {
    id: "wait-for-me",
    text: "Attends-moi.",
    missing: "Attends-moi",
    translations: { en: "Wait for me.", be: "Пачакай мяне." },
    options: ["Attends-moi", "Enchantée", "Maintenant"],
  },
  {
    id: "i-am-home",
    text: "Je suis à la maison.",
    missing: "maison",
    translations: { en: "I am at home.", be: "Я дома." },
    options: ["maison", "gare", "rue"],
  },
  {
    id: "open-door",
    text: "Ouvre la porte.",
    missing: "porte",
    translations: { en: "Open the door.", be: "Адчыні дзверы." },
    options: ["porte", "fenêtre", "table"],
  },
  {
    id: "close-window",
    text: "Ferme la fenêtre.",
    missing: "fenêtre",
    translations: { en: "Close the window.", be: "Зачыні акно." },
    options: ["fenêtre", "chaise", "clé"],
  },
  {
    id: "i-like-it",
    text: "J’aime ça.",
    missing: "aime",
    translations: { en: "I like it.", be: "Мне гэта падабаецца." },
    options: ["aime", "paie", "tourne"],
  },
  {
    id: "i-do-not-like-it",
    text: "Je n’aime pas ça.",
    missing: "aime",
    translations: { en: "I do not like it.", be: "Мне гэта не падабаецца." },
    options: ["aime", "arrive", "cherche"],
  },
  {
    id: "it-is-good",
    text: "C’est bon.",
    missing: "bon",
    translations: { en: "It is good.", be: "Гэта добра." },
    options: ["bon", "grand", "cher"],
  },
];
