export const uiText = {
  en: {
    appLabel: "French practice",
    title: "French Garden",
    languageLabel: "App language",
    levelPill: "Beginner friendly",
    heroTitle: "Tiny French steps, every day.",
    heroCopy:
      "Learn useful words, simple phrases, listening, and pronunciation in short playful rounds.",
    scoreLabel: "Score",
    streakLabel: "Good answers",
    learnedLabel: "Practiced",
    cardsTab: "Cards",
    quizTab: "Quiz",
    matchTab: "Match",
    phrasesTab: "Phrases",
    cardsEyebrow: "Vocabulary",
    cardsTitle: "Tap, listen, remember",
    listenButton: "Listen",
    quizEyebrow: "Quick quiz",
    quizTitle: "Choose the meaning",
    quizPrompt: "What does this mean?",
    matchEyebrow: "Memory match",
    matchTitle: "Pair French with meaning",
    resetButton: "Reset",
    phrasesEyebrow: "Useful phrases",
    phrasesTitle: "Complete the sentence",
    listenPhraseButton: "Hear phrase",
    correct: "Nice! That is correct.",
    wrong: "Almost. Try this one again.",
    matched: "Matched!",
  },
  be: {
    appLabel: "Практыка французскай",
    title: "Французскі сад",
    languageLabel: "Мова праграмы",
    levelPill: "Для пачаткоўцаў",
    heroTitle: "Маленькія крокі па-французску кожны дзень.",
    heroCopy:
      "Вучы карысныя словы, простыя фразы, слуханне і вымаўленне ў кароткіх гульнях.",
    scoreLabel: "Балы",
    streakLabel: "Добрыя адказы",
    learnedLabel: "Практыка",
    cardsTab: "Карткі",
    quizTab: "Тэст",
    matchTab: "Пары",
    phrasesTab: "Фразы",
    cardsEyebrow: "Слоўнік",
    cardsTitle: "Націсні, паслухай, запомні",
    listenButton: "Слухаць",
    quizEyebrow: "Хуткі тэст",
    quizTitle: "Абяры значэнне",
    quizPrompt: "Што гэта значыць?",
    matchEyebrow: "Гульня на памяць",
    matchTitle: "Знайдзі пару",
    resetButton: "Скінуць",
    phrasesEyebrow: "Карысныя фразы",
    phrasesTitle: "Дапоўні сказ",
    listenPhraseButton: "Паслухаць фразу",
    correct: "Выдатна! Правільна.",
    wrong: "Амаль. Паспрабуй яшчэ раз.",
    matched: "Пара знойдзена!",
  },
};

export const vocabulary = [
  {
    id: "hello",
    category: "Greetings",
    french: "bonjour",
    translations: { en: "hello", be: "прывітанне" },
  },
  {
    id: "thanks",
    category: "Politeness",
    french: "merci",
    translations: { en: "thank you", be: "дзякуй" },
  },
  {
    id: "please",
    category: "Politeness",
    french: "s’il te plaît",
    translations: { en: "please", be: "калі ласка" },
  },
  {
    id: "water",
    category: "Daily life",
    french: "de l’eau",
    translations: { en: "water", be: "вада" },
  },
  {
    id: "bread",
    category: "Food",
    french: "du pain",
    translations: { en: "bread", be: "хлеб" },
  },
  {
    id: "coffee",
    category: "Food",
    french: "un café",
    translations: { en: "a coffee", be: "кава" },
  },
  {
    id: "house",
    category: "Home",
    french: "la maison",
    translations: { en: "the house", be: "дом" },
  },
  {
    id: "phone",
    category: "Daily life",
    french: "le téléphone",
    translations: { en: "the phone", be: "тэлефон" },
  },
  {
    id: "today",
    category: "Time",
    french: "aujourd’hui",
    translations: { en: "today", be: "сёння" },
  },
  {
    id: "tomorrow",
    category: "Time",
    french: "demain",
    translations: { en: "tomorrow", be: "заўтра" },
  },
  {
    id: "happy",
    category: "Feelings",
    french: "content",
    translations: { en: "happy", be: "рады" },
  },
  {
    id: "tired",
    category: "Feelings",
    french: "fatiguée",
    translations: { en: "tired", be: "стомленая" },
  },
];

export const phrases = [
  {
    id: "how-are-you",
    text: "Comment ça va ?",
    missing: "ça va",
    translations: {
      en: "How are you?",
      be: "Як справы?",
    },
    options: ["ça va", "maison", "demain"],
  },
  {
    id: "i-want-water",
    text: "Je voudrais de l’eau.",
    missing: "de l’eau",
    translations: {
      en: "I would like some water.",
      be: "Я хацела б вады.",
    },
    options: ["du pain", "de l’eau", "merci"],
  },
  {
    id: "where-is-phone",
    text: "Où est mon téléphone ?",
    missing: "téléphone",
    translations: {
      en: "Where is my phone?",
      be: "Дзе мой тэлефон?",
    },
    options: ["café", "téléphone", "maison"],
  },
  {
    id: "i-am-tired",
    text: "Je suis fatiguée.",
    missing: "fatiguée",
    translations: {
      en: "I am tired.",
      be: "Я стомленая.",
    },
    options: ["content", "bonjour", "fatiguée"],
  },
  {
    id: "see-you-tomorrow",
    text: "À demain !",
    missing: "demain",
    translations: {
      en: "See you tomorrow!",
      be: "Да заўтра!",
    },
    options: ["demain", "pain", "eau"],
  },
];
