export const phrases = [
  {
    id: "how-are-you",
    text: "Comment ça va ?",
    missing: "ça va",
    translations: {
      en: "How are you?",
      be: "Як справы?",
    },
    options: ["ça va", "maison", "demain"],
  },
  {
    id: "i-want-water",
    text: "Je voudrais de l’eau.",
    missing: "de l’eau",
    translations: {
      en: "I would like some water.",
      be: "Я хацела б вады.",
    },
    options: ["du pain", "de l’eau", "merci"],
  },
  {
    id: "where-is-phone",
    text: "Où est mon téléphone ?",
    missing: "téléphone",
    translations: {
      en: "Where is my phone?",
      be: "Дзе мой тэлефон?",
    },
    options: ["café", "téléphone", "maison"],
  },
  {
    id: "i-am-tired",
    text: "Je suis fatiguée.",
    missing: "fatiguée",
    translations: {
      en: "I am tired.",
      be: "Я стомленая.",
    },
    options: ["content", "bonjour", "fatiguée"],
  },
  {
    id: "see-you-tomorrow",
    text: "À demain !",
    missing: "demain",
    translations: {
      en: "See you tomorrow!",
      be: "Да заўтра!",
    },
    options: ["demain", "pain", "eau"],
  },
  {
    id: "good-morning",
    text: "Bonjour, ça va ?",
    missing: "Bonjour",
    translations: { en: "Hello, how are you?", be: "Прывітанне, як справы?" },
    options: ["Bonjour", "Merci", "Demain"],
  },
  {
    id: "thank-you-very-much",
    text: "Merci beaucoup.",
    missing: "beaucoup",
    translations: { en: "Thank you very much.", be: "Вялікі дзякуй." },
    options: ["beaucoup", "gauche", "maison"],
  },
  {
    id: "i-do-not-understand",
    text: "Je ne comprends pas.",
    missing: "comprends",
    translations: { en: "I do not understand.", be: "Я не разумею." },
    options: ["comprends", "voudrais", "mange"],
  },
  {
    id: "repeat-please",
    text: "Tu peux répéter, s’il te plaît ?",
    missing: "répéter",
    translations: { en: "Can you repeat, please?", be: "Можаш паўтарыць, калі ласка?" },
    options: ["répéter", "acheter", "dormir"],
  },
  {
    id: "speak-slowly",
    text: "Parle lentement, s’il te plaît.",
    missing: "lentement",
    translations: { en: "Speak slowly, please.", be: "Гавары павольна, калі ласка." },
    options: ["lentement", "demain", "chaud"],
  },
  {
    id: "my-name-is",
    text: "Je m’appelle Anna.",
    missing: "m’appelle",
    translations: { en: "My name is Anna.", be: "Мяне завуць Анна." },
    options: ["m’appelle", "voudrais", "cherche"],
  },
  {
    id: "nice-to-meet-you",
    text: "Enchantée.",
    missing: "Enchantée",
    translations: { en: "Nice to meet you.", be: "Прыемна пазнаёміцца." },
    options: ["Enchantée", "Fatiguée", "Gauche"],
  },
  {
    id: "i-live-here",
    text: "J’habite ici.",
    missing: "ici",
    translations: { en: "I live here.", be: "Я жыву тут." },
    options: ["ici", "pain", "train"],
  },
  {
    id: "i-am-belarusian",
    text: "Je suis biélorusse.",
    missing: "biélorusse",
    translations: { en: "I am Belarusian.", be: "Я беларуска." },
    options: ["biélorusse", "fatiguée", "droite"],
  },
  {
    id: "i-speak-a-little",
    text: "Je parle un peu français.",
    missing: "un peu",
    translations: { en: "I speak a little French.", be: "Я крыху гавару па-французску." },
    options: ["un peu", "beaucoup", "tout droit"],
  },
  {
    id: "i-want-coffee",
    text: "Je voudrais un café.",
    missing: "café",
    translations: { en: "I would like a coffee.", be: "Я хацела б каву." },
    options: ["café", "clé", "gare"],
  },
  {
    id: "i-want-tea",
    text: "Je voudrais du thé.",
    missing: "thé",
    translations: { en: "I would like tea.", be: "Я хацела б гарбаты." },
    options: ["thé", "lit", "sac"],
  },
  {
    id: "without-sugar",
    text: "Sans sucre, s’il vous plaît.",
    missing: "sucre",
    translations: { en: "Without sugar, please.", be: "Без цукру, калі ласка." },
    options: ["sucre", "sel", "ticket"],
  },
  {
    id: "with-milk",
    text: "Avec du lait.",
    missing: "lait",
    translations: { en: "With milk.", be: "З малаком." },
    options: ["lait", "riz", "rue"],
  },
  {
    id: "i-am-hungry",
    text: "J’ai faim.",
    missing: "faim",
    translations: { en: "I am hungry.", be: "Я галодная." },
    options: ["faim", "froid", "chaud"],
  },
  {
    id: "i-am-thirsty",
    text: "J’ai soif.",
    missing: "soif",
    translations: { en: "I am thirsty.", be: "Я хачу піць." },
    options: ["soif", "soupe", "soir"],
  },
  {
    id: "where-is-bathroom",
    text: "Où sont les toilettes ?",
    missing: "toilettes",
    translations: { en: "Where are the toilets?", be: "Дзе туалет?" },
    options: ["toilettes", "fenêtres", "pommes"],
  },
  {
    id: "where-is-station",
    text: "Où est la gare ?",
    missing: "gare",
    translations: { en: "Where is the train station?", be: "Дзе вакзал?" },
    options: ["gare", "chaise", "banane"],
  },
  {
    id: "where-is-shop",
    text: "Où est le magasin ?",
    missing: "magasin",
    translations: { en: "Where is the shop?", be: "Дзе крама?" },
    options: ["magasin", "médecin", "poisson"],
  },
  {
    id: "turn-left",
    text: "Tourne à gauche.",
    missing: "gauche",
    translations: { en: "Turn left.", be: "Павярні налева." },
    options: ["gauche", "droite", "ici"],
  },
  {
    id: "turn-right",
    text: "Tourne à droite.",
    missing: "droite",
    translations: { en: "Turn right.", be: "Павярні направа." },
    options: ["droite", "gauche", "demain"],
  },
  {
    id: "go-straight",
    text: "Va tout droit.",
    missing: "droit",
    translations: { en: "Go straight ahead.", be: "Ідзі прама." },
    options: ["droit", "soir", "sac"],
  },
  {
    id: "how-much",
    text: "Ça coûte combien ?",
    missing: "combien",
    translations: { en: "How much does it cost?", be: "Колькі гэта каштуе?" },
    options: ["combien", "comment", "bonjour"],
  },
  {
    id: "too-expensive",
    text: "C’est trop cher.",
    missing: "cher",
    translations: { en: "It is too expensive.", be: "Гэта занадта дорага." },
    options: ["cher", "froid", "petit"],
  },
  {
    id: "i-pay-card",
    text: "Je paie par carte.",
    missing: "carte",
    translations: { en: "I pay by card.", be: "Я плачу картай." },
    options: ["carte", "clé", "pomme"],
  },
  {
    id: "receipt-please",
    text: "Le ticket, s’il vous plaît.",
    missing: "ticket",
    translations: { en: "The receipt, please.", be: "Чэк, калі ласка." },
    options: ["ticket", "train", "thé"],
  },
  {
    id: "i-am-cold",
    text: "J’ai froid.",
    missing: "froid",
    translations: { en: "I am cold.", be: "Мне холадна." },
    options: ["froid", "chaud", "faim"],
  },
  {
    id: "i-am-hot",
    text: "J’ai chaud.",
    missing: "chaud",
    translations: { en: "I am hot.", be: "Мне горача." },
    options: ["chaud", "froid", "soif"],
  },
  {
    id: "my-head-hurts",
    text: "J’ai mal à la tête.",
    missing: "tête",
    translations: { en: "My head hurts.", be: "У мяне баліць галава." },
    options: ["tête", "porte", "riz"],
  },
  {
    id: "i-need-doctor",
    text: "J’ai besoin d’un médecin.",
    missing: "médecin",
    translations: { en: "I need a doctor.", be: "Мне патрэбен доктар." },
    options: ["médecin", "magasin", "métro"],
  },
  {
    id: "i-need-medicine",
    text: "J’ai besoin d’un médicament.",
    missing: "médicament",
    translations: { en: "I need medicine.", be: "Мне патрэбныя лекі." },
    options: ["médicament", "restaurant", "fromage"],
  },
  {
    id: "i-am-lost",
    text: "Je suis perdue.",
    missing: "perdue",
    translations: { en: "I am lost.", be: "Я заблудзілася." },
    options: ["perdue", "content", "beau"],
  },
  {
    id: "help-me",
    text: "Aide-moi, s’il te plaît.",
    missing: "Aide-moi",
    translations: { en: "Help me, please.", be: "Дапамажы мне, калі ласка." },
    options: ["Aide-moi", "Bonjour", "À demain"],
  },
  {
    id: "call-me",
    text: "Appelle-moi.",
    missing: "Appelle-moi",
    translations: { en: "Call me.", be: "Патэлефануй мне." },
    options: ["Appelle-moi", "Tourne", "Mange"],
  },
  {
    id: "i-am-coming",
    text: "J’arrive.",
    missing: "arrive",
    translations: { en: "I am coming.", be: "Я іду." },
    options: ["arrive", "habite", "coûte"],
  },
  {
    id: "wait-for-me",
    text: "Attends-moi.",
    missing: "Attends-moi",
    translations: { en: "Wait for me.", be: "Пачакай мяне." },
    options: ["Attends-moi", "Enchantée", "Maintenant"],
  },
  {
    id: "i-am-home",
    text: "Je suis à la maison.",
    missing: "maison",
    translations: { en: "I am at home.", be: "Я дома." },
    options: ["maison", "gare", "rue"],
  },
  {
    id: "open-door",
    text: "Ouvre la porte.",
    missing: "porte",
    translations: { en: "Open the door.", be: "Адчыні дзверы." },
    options: ["porte", "fenêtre", "table"],
  },
  {
    id: "close-window",
    text: "Ferme la fenêtre.",
    missing: "fenêtre",
    translations: { en: "Close the window.", be: "Зачыні акно." },
    options: ["fenêtre", "chaise", "clé"],
  },
  {
    id: "i-like-it",
    text: "J’aime ça.",
    missing: "aime",
    translations: { en: "I like it.", be: "Мне гэта падабаецца." },
    options: ["aime", "paie", "tourne"],
  },
  {
    id: "i-do-not-like-it",
    text: "Je n’aime pas ça.",
    missing: "aime",
    translations: { en: "I do not like it.", be: "Мне гэта не падабаецца." },
    options: ["aime", "arrive", "cherche"],
  },
  {
    id: "it-is-good",
    text: "C’est bon.",
    missing: "bon",
    translations: { en: "It is good.", be: "Гэта добра." },
    options: ["bon", "grand", "cher"],
  },
  {
    id: "i-want-manicure",
    text: "Je voudrais une manucure.",
    missing: "manucure",
    translations: { en: "I would like a manicure.", be: "Я хацела б манікюр." },
    options: ["manucure", "pédicure", "couleur"],
  },
  {
    id: "i-have-appointment",
    text: "J’ai rendez-vous.",
    missing: "rendez-vous",
    translations: { en: "I have an appointment.", be: "У мяне ёсць запіс." },
    options: ["rendez-vous", "paillettes", "cuticules"],
  },
  {
    id: "what-colors",
    text: "Vous avez quelles couleurs ?",
    missing: "couleurs",
    translations: { en: "What colors do you have?", be: "Якія ў вас ёсць колеры?" },
    options: ["couleurs", "ongles", "lampes"],
  },
  {
    id: "i-want-this-color",
    text: "Je voudrais cette couleur.",
    missing: "couleur",
    translations: { en: "I would like this color.", be: "Я хацела б гэты колер." },
    options: ["couleur", "forme", "lime"],
  },
  {
    id: "short-please",
    text: "Court, s’il vous plaît.",
    missing: "Court",
    translations: { en: "Short, please.", be: "Каротка, калі ласка." },
    options: ["Court", "Long", "Rouge"],
  },
  {
    id: "almond-shape-please",
    text: "En amande, s’il vous plaît.",
    missing: "amande",
    translations: { en: "Almond shaped, please.", be: "Міндалепадобную форму, калі ласка." },
    options: ["amande", "carte", "gare"],
  },
  {
    id: "no-glitter",
    text: "Sans paillettes, s’il vous plaît.",
    missing: "paillettes",
    translations: { en: "No glitter, please.", be: "Без бліскавак, калі ласка." },
    options: ["paillettes", "sucre", "ticket"],
  },
  {
    id: "with-gel-polish",
    text: "Avec du vernis semi-permanent.",
    missing: "semi-permanent",
    translations: { en: "With gel polish.", be: "З гель-лакам." },
    options: ["semi-permanent", "lentement", "maintenant"],
  },
  {
    id: "how-long-nails",
    text: "Ça dure combien de temps ?",
    missing: "temps",
    translations: { en: "How long does it take?", be: "Колькі гэта зойме часу?" },
    options: ["temps", "couleur", "vernis"],
  },
  {
    id: "is-it-possible",
    text: "C’est possible ?",
    missing: "possible",
    translations: { en: "Is it possible?", be: "Гэта магчыма?" },
    options: ["possible", "petit", "malade"],
  },
  {
    id: "can-i-have-menu",
    text: "Je peux avoir le menu ?",
    missing: "menu",
    translations: { en: "Can I have the menu?", be: "Можна мне меню?" },
    options: ["menu", "médecin", "métro"],
  },
  {
    id: "bill-please",
    text: "L’addition, s’il vous plaît.",
    missing: "addition",
    translations: { en: "The bill, please.", be: "Рахунак, калі ласка." },
    options: ["addition", "adresse", "amande"],
  },
  {
    id: "where-is-exit",
    text: "Où est la sortie ?",
    missing: "sortie",
    translations: { en: "Where is the exit?", be: "Дзе выхад?" },
    options: ["sortie", "soupe", "soif"],
  },
  {
    id: "i-am-late",
    text: "Je suis en retard.",
    missing: "retard",
    translations: { en: "I am late.", be: "Я спазняюся." },
    options: ["retard", "rendez-vous", "rouge"],
  },
  {
    id: "can-i-pay-card",
    text: "Je peux payer par carte ?",
    missing: "carte",
    translations: { en: "Can I pay by card?", be: "Можна аплаціць картай?" },
    options: ["carte", "clé", "couleur"],
  },
  {
    id: "i-need-charger",
    text: "J’ai besoin d’un chargeur.",
    missing: "chargeur",
    translations: { en: "I need a charger.", be: "Мне патрэбна зарадная прылада." },
    options: ["chargeur", "couteau", "carré"],
  },
  {
    id: "is-it-open",
    text: "C’est ouvert ?",
    missing: "ouvert",
    translations: { en: "Is it open?", be: "Гэта адчынена?" },
    options: ["ouvert", "fermé", "fatiguée"],
  },
  {
    id: "i-would-like-taxi",
    text: "Je voudrais un taxi.",
    missing: "taxi",
    translations: { en: "I would like a taxi.", be: "Я хацела б таксі." },
    options: ["taxi", "thé", "taille"],
  },
];
