export const uiText = {
  en: {
    appLabel: "French practice",
    title: "French Garden",
    languageLabel: "App language",
    levelPill: "Beginner friendly",
    heroTitle: "Tiny French steps, every day.",
    heroCopy: "Learn useful words and simple phrases in short playful rounds.",
    todayEyebrow: "Daily session",
    todayTitle: "Today’s Garden",
    todayCopy: "A short mixed round with review words, pictures, and phrases.",
    todayStartButton: "Start today’s practice",
    todayProgressLabel: "Step {current} of {total}",
    todayQuizLabel: "Meaning",
    todayPictureLabel: "Picture",
    todayPhraseLabel: "Phrase",
    todayCardLabel: "Review card",
    todayCorrectAnswer: "Answer: {answer}",
    todayNextButton: "Next step",
    todayFinishButton: "Finish",
    todayCompleteLabel: "Complete",
    todaySummaryTitle: "Garden complete",
    todaySummaryStats: "{correct}/{total} correct · +{score} points",
    todaySummaryReview: "Review next: {items}",
    todaySummaryClean: "Nothing new to review from this round.",
    todayPracticeAgain: "Practice again",
    todayEmptyTitle: "No daily round yet",
    todayEmptyCopy: "Try another level or turn off Review only to build a mixed session.",
    scoreLabel: "Score",
    streakLabel: "Good answers",
    learnedLabel: "Practiced",
    reviewLabel: "To review",
    levelFilterLabel: "Level",
    categoryFilterLabel: "Category",
    reviewOnlyLabel: "Review only",
    progressEyebrow: "Progress",
    progressTitle: "Practice by category",
    progressTab: "Progress",
    rewardsEyebrow: "Rewards",
    rewardsTitle: "Little rewards from Sylvain",
    rewardListInstructions:
      "Open an unlocked reward, copy the reward image, then paste it in a message to Sylvain.",
    rewardUnlockedEyebrow: "Reward unlocked",
    rewardForAnswers: "After {count} good answers",
    rewardLocked: "{count} good answers to unlock",
    mysteryReward: "Mystery reward",
    copyRewardButton: "Share or copy reward image",
    rewardCopyInstructions:
      "Tap Share or copy reward image, then send or paste it to Sylvain.",
    closeRewardButton: "Close",
    rewardPreparing: "Preparing the reward image...",
    rewardCopied: "Reward image copied. Now paste it in a message to Sylvain.",
    rewardShared: "Reward image ready. Send it to Sylvain from the share sheet.",
    rewardCopyFallback:
      "Image copy is not available here, so the reward text was copied instead.",
    rewardMessageBody:
      "I unlocked this reward in French Garden: {reward}. Good answers: {count}.",
    cardsTab: "Cards",
    quizTab: "Quiz",
    picturesTab: "Pictures",
    matchTab: "Match",
    phrasesTab: "Phrases",
    situationsTab: "Situations",
    cardsEyebrow: "Vocabulary",
    cardsTitle: "Tap, learn, remember",
    newCardTitle: "New card",
    previousButton: "Previous",
    nextButton: "Next",
    knowButton: "I know it",
    reviewButton: "Review later",
    quizEyebrow: "Quick quiz",
    quizTitle: "Choose the meaning",
    quizPrompt: "What does this mean?",
    picturesEyebrow: "Picture quiz",
    picturesTitle: "Look, then pick French",
    picturesPrompt: "What is this in French?",
    matchEyebrow: "Memory match",
    matchTitle: "Pair French with meaning",
    matchFrenchLabel: "French words",
    matchMeaningLabel: "English words",
    resetButton: "Reset",
    phrasesEyebrow: "Useful phrases",
    phrasesTitle: "Complete the sentence",
    situationsEyebrow: "Mini situations",
    situationsTitle: "Practice real moments",
    practiceButton: "Practice",
    correct: "Nice! That is correct.",
    wrong: "Almost. Try this one again.",
    combo: "Combo!",
    matched: "Matched!",
    allLevels: "All levels",
    allCategories: "All categories",
    level: "Level",
    level1: "Level 1",
    level2: "Level 2",
    level3: "Level 3",
    emptyReview: "Nothing to review yet. Mark words for review or miss a quiz answer.",
    emptyPractice: "Nothing here yet for these filters.",
  },
  be: {
    appLabel: "Практыка французскай",
    title: "Французскі сад",
    languageLabel: "Мова праграмы",
    levelPill: "Для пачаткоўцаў",
    heroTitle: "Маленькія крокі па-французску кожны дзень.",
    heroCopy: "Вучы карысныя словы і простыя фразы ў кароткіх гульнях.",
    todayEyebrow: "Штодзённая практыка",
    todayTitle: "Сённяшні сад",
    todayCopy: "Кароткі мікс са словамі на паўтор, малюнкамі і фразамі.",
    todayStartButton: "Пачаць сённяшнюю практыку",
    todayProgressLabel: "Крок {current} з {total}",
    todayQuizLabel: "Значэнне",
    todayPictureLabel: "Малюнак",
    todayPhraseLabel: "Фраза",
    todayCardLabel: "Картка на паўтор",
    todayCorrectAnswer: "Адказ: {answer}",
    todayNextButton: "Наступны крок",
    todayFinishButton: "Завяршыць",
    todayCompleteLabel: "Гатова",
    todaySummaryTitle: "Сад завершаны",
    todaySummaryStats: "{correct}/{total} правільна · +{score} балаў",
    todaySummaryReview: "Паўтары далей: {items}",
    todaySummaryClean: "З гэтага раўнда няма нічога новага на паўтор.",
    todayPracticeAgain: "Практыкаваць яшчэ",
    todayEmptyTitle: "Пакуль няма штодзённага раўнда",
    todayEmptyCopy: "Паспрабуй іншы ўзровень або выключы толькі паўтор.",
    scoreLabel: "Балы",
    streakLabel: "Добрыя адказы",
    learnedLabel: "Практыка",
    reviewLabel: "На паўтор",
    levelFilterLabel: "Узровень",
    categoryFilterLabel: "Катэгорыя",
    reviewOnlyLabel: "Толькі паўтор",
    progressEyebrow: "Прагрэс",
    progressTitle: "Практыка па катэгорыях",
    progressTab: "Прагрэс",
    rewardsEyebrow: "Узнагароды",
    rewardsTitle: "Маленькія ўзнагароды ад Сільвэна",
    rewardListInstructions:
      "Адкрый узнагароду, скапіруй выяву і ўстаў яе ў паведамленне Сільвэну.",
    rewardUnlockedEyebrow: "Узнагарода адкрыта",
    rewardForAnswers: "Пасля {count} добрых адказаў",
    rewardLocked: "{count} добрых адказаў, каб адкрыць",
    mysteryReward: "Таямнічая ўзнагарода",
    copyRewardButton: "Падзяліцца або скапіраваць выяву",
    rewardCopyInstructions:
      "Націсні, каб падзяліцца або скапіраваць выяву, потым адпраў яе Сільвэну.",
    closeRewardButton: "Закрыць",
    rewardPreparing: "Рыхтуем выяву ўзнагароды...",
    rewardCopied: "Выява ўзнагароды скапіравана. Цяпер устаў яе ў паведамленне Сільвэну.",
    rewardShared: "Выява ўзнагароды гатовая. Адпраў яе Сільвэну з меню падзяліцца.",
    rewardCopyFallback:
      "Тут нельга скапіраваць выяву, таму тэкст узнагароды быў скапіраваны.",
    rewardMessageBody:
      "Я адкрыла гэтую ўзнагароду ў French Garden: {reward}. Добрых адказаў: {count}.",
    cardsTab: "Карткі",
    quizTab: "Тэст",
    picturesTab: "Малюнкі",
    matchTab: "Пары",
    phrasesTab: "Фразы",
    situationsTab: "Сітуацыі",
    cardsEyebrow: "Слоўнік",
    cardsTitle: "Націсні, вучы, запомні",
    newCardTitle: "Новая картка",
    previousButton: "Назад",
    nextButton: "Далей",
    knowButton: "Я ведаю",
    reviewButton: "Паўтарыць пазней",
    quizEyebrow: "Хуткі тэст",
    quizTitle: "Абяры значэнне",
    quizPrompt: "Што гэта значыць?",
    picturesEyebrow: "Тэст з малюнкамі",
    picturesTitle: "Паглядзі і абяры французскае слова",
    picturesPrompt: "Як гэта па-французску?",
    matchEyebrow: "Гульня на памяць",
    matchTitle: "Знайдзі пару",
    matchFrenchLabel: "Французскія словы",
    matchMeaningLabel: "Англійскія словы",
    resetButton: "Скінуць",
    phrasesEyebrow: "Карысныя фразы",
    phrasesTitle: "Дапоўні сказ",
    situationsEyebrow: "Міні-сітуацыі",
    situationsTitle: "Практыка сапраўдных момантаў",
    practiceButton: "Практыкаваць",
    correct: "Выдатна! Правільна.",
    wrong: "Амаль. Паспрабуй яшчэ раз.",
    combo: "Серыя!",
    matched: "Пара знойдзена!",
    allLevels: "Усе ўзроўні",
    allCategories: "Усе катэгорыі",
    level: "Узровень",
    level1: "Узровень 1",
    level2: "Узровень 2",
    level3: "Узровень 3",
    emptyReview: "Пакуль няма слоў на паўтор. Адзнач словы або памыліся ў тэсце.",
    emptyPractice: "Пакуль тут нічога няма для гэтых фільтраў.",
  },
};
