export const uiText = {
  en: {
    appLabel: "French practice",
    title: "French Garden",
    languageLabel: "App language",
    levelPill: "Beginner friendly",
    heroTitle: "Tiny French steps, every day.",
    heroCopy:
      "Learn useful words, simple phrases, listening, and pronunciation in short playful rounds.",
    scoreLabel: "Score",
    streakLabel: "Good answers",
    learnedLabel: "Practiced",
    reviewLabel: "To review",
    levelFilterLabel: "Level",
    categoryFilterLabel: "Category",
    reviewOnlyLabel: "Review only",
    progressEyebrow: "Progress",
    progressTitle: "Practice by category",
    progressTab: "Progress",
    cardsTab: "Cards",
    quizTab: "Quiz",
    picturesTab: "Pictures",
    matchTab: "Match",
    phrasesTab: "Phrases",
    listenTab: "Listen",
    situationsTab: "Situations",
    cardsEyebrow: "Vocabulary",
    cardsTitle: "Tap, listen, remember",
    newCardTitle: "New card",
    previousButton: "Previous",
    nextButton: "Next",
    listenButton: "Listen",
    knowButton: "I know it",
    reviewButton: "Review later",
    quizEyebrow: "Quick quiz",
    quizTitle: "Choose the meaning",
    quizPrompt: "What does this mean?",
    picturesEyebrow: "Picture quiz",
    picturesTitle: "Look, then pick French",
    picturesPrompt: "What is this in French?",
    matchEyebrow: "Memory match",
    matchTitle: "Pair French with meaning",
    matchFrenchLabel: "French words",
    matchMeaningLabel: "English words",
    resetButton: "Reset",
    phrasesEyebrow: "Useful phrases",
    phrasesTitle: "Complete the sentence",
    listenPhraseButton: "Hear phrase",
    listenEyebrow: "Listening",
    listenTitle: "Hear French, choose meaning",
    listenPrompt: "Listen, then choose the meaning.",
    playAudioButton: "Play audio",
    situationsEyebrow: "Mini situations",
    situationsTitle: "Practice real moments",
    practiceButton: "Practice",
    correct: "Nice! That is correct.",
    wrong: "Almost. Try this one again.",
    combo: "Combo!",
    matched: "Matched!",
    allLevels: "All levels",
    allCategories: "All categories",
    level: "Level",
    level1: "Level 1",
    level2: "Level 2",
    level3: "Level 3",
    emptyReview: "Nothing to review yet. Mark words for review or miss a quiz answer.",
  },
  be: {
    appLabel: "Практыка французскай",
    title: "Французскі сад",
    languageLabel: "Мова праграмы",
    levelPill: "Для пачаткоўцаў",
    heroTitle: "Маленькія крокі па-французску кожны дзень.",
    heroCopy:
      "Вучы карысныя словы, простыя фразы, слуханне і вымаўленне ў кароткіх гульнях.",
    scoreLabel: "Балы",
    streakLabel: "Добрыя адказы",
    learnedLabel: "Практыка",
    reviewLabel: "На паўтор",
    levelFilterLabel: "Узровень",
    categoryFilterLabel: "Катэгорыя",
    reviewOnlyLabel: "Толькі паўтор",
    progressEyebrow: "Прагрэс",
    progressTitle: "Практыка па катэгорыях",
    progressTab: "Прагрэс",
    cardsTab: "Карткі",
    quizTab: "Тэст",
    picturesTab: "Малюнкі",
    matchTab: "Пары",
    phrasesTab: "Фразы",
    listenTab: "Слуханне",
    situationsTab: "Сітуацыі",
    cardsEyebrow: "Слоўнік",
    cardsTitle: "Націсні, паслухай, запомні",
    newCardTitle: "Новая картка",
    previousButton: "Назад",
    nextButton: "Далей",
    listenButton: "Слухаць",
    knowButton: "Я ведаю",
    reviewButton: "Паўтарыць пазней",
    quizEyebrow: "Хуткі тэст",
    quizTitle: "Абяры значэнне",
    quizPrompt: "Што гэта значыць?",
    picturesEyebrow: "Тэст з малюнкамі",
    picturesTitle: "Паглядзі і абяры французскае слова",
    picturesPrompt: "Як гэта па-французску?",
    matchEyebrow: "Гульня на памяць",
    matchTitle: "Знайдзі пару",
    matchFrenchLabel: "Французскія словы",
    matchMeaningLabel: "Англійскія словы",
    resetButton: "Скінуць",
    phrasesEyebrow: "Карысныя фразы",
    phrasesTitle: "Дапоўні сказ",
    listenPhraseButton: "Паслухаць фразу",
    listenEyebrow: "Слуханне",
    listenTitle: "Паслухай французскую і абяры значэнне",
    listenPrompt: "Паслухай, потым абяры значэнне.",
    playAudioButton: "Прайграць аўдыя",
    situationsEyebrow: "Міні-сітуацыі",
    situationsTitle: "Практыка сапраўдных момантаў",
    practiceButton: "Практыкаваць",
    correct: "Выдатна! Правільна.",
    wrong: "Амаль. Паспрабуй яшчэ раз.",
    combo: "Серыя!",
    matched: "Пара знойдзена!",
    allLevels: "Усе ўзроўні",
    allCategories: "Усе катэгорыі",
    level: "Узровень",
    level1: "Узровень 1",
    level2: "Узровень 2",
    level3: "Узровень 3",
    emptyReview: "Пакуль няма слоў на паўтор. Адзнач словы або памыліся ў тэсце.",
  },
};
