export const vocabulary = [
  { id: "hello", category: "Greetings", french: "bonjour", translations: { en: "hello", be: "прывітанне" } },
  { id: "good-evening", category: "Greetings", french: "bonsoir", translations: { en: "good evening", be: "добры вечар" } },
  { id: "goodbye", category: "Greetings", french: "au revoir", translations: { en: "goodbye", be: "да пабачэння" } },
  { id: "see-you-soon", category: "Greetings", french: "à bientôt", translations: { en: "see you soon", be: "да хуткай сустрэчы" } },
  { id: "thanks", category: "Politeness", french: "merci", translations: { en: "thank you", be: "дзякуй" } },
  { id: "please", category: "Politeness", french: "s’il te plaît", translations: { en: "please", be: "калі ласка" } },
  { id: "sorry", category: "Politeness", french: "pardon", translations: { en: "sorry", be: "прабач" } },
  { id: "yes", category: "Basics", french: "oui", translations: { en: "yes", be: "так" } },
  { id: "no", category: "Basics", french: "non", translations: { en: "no", be: "не" } },
  { id: "maybe", category: "Basics", french: "peut-être", translations: { en: "maybe", be: "магчыма" } },
  { id: "here", category: "Basics", french: "ici", translations: { en: "here", be: "тут" } },
  { id: "there", category: "Basics", french: "là-bas", translations: { en: "over there", be: "там" } },
  { id: "water", category: "Food", french: "de l’eau", translations: { en: "water", be: "вада" } },
  { id: "bread", category: "Food", french: "du pain", translations: { en: "bread", be: "хлеб" } },
  { id: "coffee", category: "Food", french: "un café", translations: { en: "a coffee", be: "кава" } },
  { id: "tea", category: "Food", french: "du thé", translations: { en: "tea", be: "гарбата" } },
  { id: "milk", category: "Food", french: "du lait", translations: { en: "milk", be: "малако" } },
  { id: "sugar", category: "Food", french: "du sucre", translations: { en: "sugar", be: "цукар" } },
  { id: "salt", category: "Food", french: "du sel", translations: { en: "salt", be: "соль" } },
  { id: "apple", category: "Food", french: "une pomme", translations: { en: "an apple", be: "яблык" } },
  { id: "banana", category: "Food", french: "une banane", translations: { en: "a banana", be: "банан" } },
  { id: "cheese", category: "Food", french: "du fromage", translations: { en: "cheese", be: "сыр" } },
  { id: "rice", category: "Food", french: "du riz", translations: { en: "rice", be: "рыс" } },
  { id: "soup", category: "Food", french: "de la soupe", translations: { en: "soup", be: "суп" } },
  { id: "chicken", category: "Food", french: "du poulet", translations: { en: "chicken", be: "курыца" } },
  { id: "fish", category: "Food", french: "du poisson", translations: { en: "fish", be: "рыба" } },
  { id: "house", category: "Home", french: "la maison", translations: { en: "the house", be: "дом" } },
  { id: "room", category: "Home", french: "la chambre", translations: { en: "the bedroom", be: "спальня" } },
  { id: "kitchen", category: "Home", french: "la cuisine", translations: { en: "the kitchen", be: "кухня" } },
  { id: "bathroom", category: "Home", french: "la salle de bain", translations: { en: "the bathroom", be: "ванны пакой" } },
  { id: "door", category: "Home", french: "la porte", translations: { en: "the door", be: "дзверы" } },
  { id: "window", category: "Home", french: "la fenêtre", translations: { en: "the window", be: "акно" } },
  { id: "table", category: "Home", french: "la table", translations: { en: "the table", be: "стол" } },
  { id: "chair", category: "Home", french: "la chaise", translations: { en: "the chair", be: "крэсла" } },
  { id: "bed", category: "Home", french: "le lit", translations: { en: "the bed", be: "ложак" } },
  { id: "key", category: "Home", french: "la clé", translations: { en: "the key", be: "ключ" } },
  { id: "phone", category: "Daily life", french: "le téléphone", translations: { en: "the phone", be: "тэлефон" } },
  { id: "bag", category: "Daily life", french: "le sac", translations: { en: "the bag", be: "сумка" } },
  { id: "book", category: "Daily life", french: "le livre", translations: { en: "the book", be: "кніга" } },
  { id: "pen", category: "Daily life", french: "le stylo", translations: { en: "the pen", be: "ручка" } },
  { id: "money", category: "Daily life", french: "l’argent", translations: { en: "money", be: "грошы" } },
  { id: "ticket", category: "Daily life", french: "le ticket", translations: { en: "the ticket", be: "білет" } },
  { id: "today", category: "Time", french: "aujourd’hui", translations: { en: "today", be: "сёння" } },
  { id: "tomorrow", category: "Time", french: "demain", translations: { en: "tomorrow", be: "заўтра" } },
  { id: "yesterday", category: "Time", french: "hier", translations: { en: "yesterday", be: "учора" } },
  { id: "morning", category: "Time", french: "le matin", translations: { en: "the morning", be: "раніца" } },
  { id: "evening", category: "Time", french: "le soir", translations: { en: "the evening", be: "вечар" } },
  { id: "now", category: "Time", french: "maintenant", translations: { en: "now", be: "зараз" } },
  { id: "later", category: "Time", french: "plus tard", translations: { en: "later", be: "пазней" } },
  { id: "monday", category: "Time", french: "lundi", translations: { en: "Monday", be: "панядзелак" } },
  { id: "friday", category: "Time", french: "vendredi", translations: { en: "Friday", be: "пятніца" } },
  { id: "happy", category: "Feelings", french: "content", translations: { en: "happy", be: "рады" } },
  { id: "tired", category: "Feelings", french: "fatiguée", translations: { en: "tired", be: "стомленая" } },
  { id: "hungry", category: "Feelings", french: "j’ai faim", translations: { en: "I am hungry", be: "я галодная" } },
  { id: "thirsty", category: "Feelings", french: "j’ai soif", translations: { en: "I am thirsty", be: "я хачу піць" } },
  { id: "cold", category: "Feelings", french: "j’ai froid", translations: { en: "I am cold", be: "мне холадна" } },
  { id: "hot", category: "Feelings", french: "j’ai chaud", translations: { en: "I am hot", be: "мне горача" } },
  { id: "sick", category: "Health", french: "malade", translations: { en: "sick", be: "хворая" } },
  { id: "head", category: "Health", french: "la tête", translations: { en: "the head", be: "галава" } },
  { id: "stomach", category: "Health", french: "le ventre", translations: { en: "the stomach", be: "жывот" } },
  { id: "medicine", category: "Health", french: "le médicament", translations: { en: "the medicine", be: "лекі" } },
  { id: "doctor", category: "Health", french: "le médecin", translations: { en: "the doctor", be: "доктар" } },
  { id: "street", category: "Places", french: "la rue", translations: { en: "the street", be: "вуліца" } },
  { id: "shop", category: "Places", french: "le magasin", translations: { en: "the shop", be: "крама" } },
  { id: "restaurant", category: "Places", french: "le restaurant", translations: { en: "the restaurant", be: "рэстаран" } },
  { id: "station", category: "Places", french: "la gare", translations: { en: "the train station", be: "вакзал" } },
  { id: "pharmacy", category: "Places", french: "la pharmacie", translations: { en: "the pharmacy", be: "аптэка" } },
  { id: "park", category: "Places", french: "le parc", translations: { en: "the park", be: "парк" } },
  { id: "car", category: "Transport", french: "la voiture", translations: { en: "the car", be: "машына" } },
  { id: "train", category: "Transport", french: "le train", translations: { en: "the train", be: "цягнік" } },
  { id: "bus", category: "Transport", french: "le bus", translations: { en: "the bus", be: "аўтобус" } },
  { id: "metro", category: "Transport", french: "le métro", translations: { en: "the metro", be: "метро" } },
  { id: "left", category: "Directions", french: "à gauche", translations: { en: "to the left", be: "налева" } },
  { id: "right", category: "Directions", french: "à droite", translations: { en: "to the right", be: "направа" } },
  { id: "straight", category: "Directions", french: "tout droit", translations: { en: "straight ahead", be: "прама" } },
  { id: "near", category: "Directions", french: "près de", translations: { en: "near", be: "каля" } },
  { id: "far", category: "Directions", french: "loin de", translations: { en: "far from", be: "далёка ад" } },
  { id: "small", category: "Descriptions", french: "petit", translations: { en: "small", be: "маленькі" } },
  { id: "big", category: "Descriptions", french: "grand", translations: { en: "big", be: "вялікі" } },
  { id: "good", category: "Descriptions", french: "bon", translations: { en: "good", be: "добры" } },
  { id: "beautiful", category: "Descriptions", french: "beau", translations: { en: "beautiful", be: "прыгожы" } },
  { id: "expensive", category: "Shopping", french: "cher", translations: { en: "expensive", be: "дарагі" } },
  { id: "cheap", category: "Shopping", french: "pas cher", translations: { en: "cheap", be: "танны" } },
  { id: "receipt", category: "Shopping", french: "le ticket de caisse", translations: { en: "the receipt", be: "чэк" } },
  { id: "nail-salon", category: "Nail salon", french: "le salon de manucure", translations: { en: "the nail salon", be: "салон манікюру" } },
  { id: "appointment", category: "Nail salon", french: "un rendez-vous", translations: { en: "an appointment", be: "запіс" } },
  { id: "manicure", category: "Nail salon", french: "une manucure", translations: { en: "a manicure", be: "манікюр" } },
  { id: "pedicure", category: "Nail salon", french: "une pédicure", translations: { en: "a pedicure", be: "педыкюр" } },
  { id: "nails", category: "Nail salon", french: "les ongles", translations: { en: "the nails", be: "ногці" } },
  { id: "nail-polish", category: "Nail salon", french: "le vernis", translations: { en: "the nail polish", be: "лак для ногцяў" } },
  { id: "gel-polish", category: "Nail salon", french: "le vernis semi-permanent", translations: { en: "gel polish", be: "гель-лак" } },
  { id: "gel-nails", category: "Nail salon", french: "les ongles en gel", translations: { en: "gel nails", be: "гелевыя ногці" } },
  { id: "color", category: "Nail salon", french: "la couleur", translations: { en: "the color", be: "колер" } },
  { id: "nude-color", category: "Nail salon", french: "nude", translations: { en: "nude", be: "нюд" } },
  { id: "pink-color", category: "Nail salon", french: "rose", translations: { en: "pink", be: "ружовы" } },
  { id: "red-color", category: "Nail salon", french: "rouge", translations: { en: "red", be: "чырвоны" } },
  { id: "white-color", category: "Nail salon", french: "blanc", translations: { en: "white", be: "белы" } },
  { id: "glitter", category: "Nail salon", french: "des paillettes", translations: { en: "glitter", be: "бліскаўкі" } },
  { id: "short-nails", category: "Nail salon", french: "court", translations: { en: "short", be: "кароткі" } },
  { id: "long-nails", category: "Nail salon", french: "long", translations: { en: "long", be: "доўгі" } },
  { id: "round-shape", category: "Nail salon", french: "rond", translations: { en: "round", be: "круглы" } },
  { id: "square-shape", category: "Nail salon", french: "carré", translations: { en: "square", be: "квадратны" } },
  { id: "almond-shape", category: "Nail salon", french: "en amande", translations: { en: "almond shaped", be: "міндалепадобны" } },
  { id: "cuticles", category: "Nail salon", french: "les cuticules", translations: { en: "the cuticles", be: "кутыкулы" } },
  { id: "file", category: "Nail salon", french: "la lime", translations: { en: "the nail file", be: "пілка для ногцяў" } },
  { id: "drying-lamp", category: "Nail salon", french: "la lampe", translations: { en: "the lamp", be: "лямпа" } },
  { id: "fork", category: "Food", french: "la fourchette", translations: { en: "the fork", be: "відэлец" } },
  { id: "knife", category: "Food", french: "le couteau", translations: { en: "the knife", be: "нож" } },
  { id: "glass", category: "Food", french: "le verre", translations: { en: "the glass", be: "шклянка" } },
  { id: "menu", category: "Food", french: "le menu", translations: { en: "the menu", be: "меню" } },
  { id: "bill", category: "Food", french: "l’addition", translations: { en: "the bill", be: "рахунак" } },
  { id: "toilet", category: "Places", french: "les toilettes", translations: { en: "the toilets", be: "туалет" } },
  { id: "hotel", category: "Places", french: "l’hôtel", translations: { en: "the hotel", be: "гатэль" } },
  { id: "bank", category: "Places", french: "la banque", translations: { en: "the bank", be: "банк" } },
  { id: "museum", category: "Places", french: "le musée", translations: { en: "the museum", be: "музей" } },
  { id: "airport", category: "Transport", french: "l’aéroport", translations: { en: "the airport", be: "аэрапорт" } },
  { id: "taxi", category: "Transport", french: "le taxi", translations: { en: "the taxi", be: "таксі" } },
  { id: "bike", category: "Transport", french: "le vélo", translations: { en: "the bike", be: "ровар" } },
  { id: "map", category: "Directions", french: "la carte", translations: { en: "the map", be: "карта" } },
  { id: "entrance", category: "Directions", french: "l’entrée", translations: { en: "the entrance", be: "уваход" } },
  { id: "exit", category: "Directions", french: "la sortie", translations: { en: "the exit", be: "выхад" } },
  { id: "open", category: "Shopping", french: "ouvert", translations: { en: "open", be: "адчынена" } },
  { id: "closed", category: "Shopping", french: "fermé", translations: { en: "closed", be: "зачынена" } },
  { id: "size", category: "Shopping", french: "la taille", translations: { en: "the size", be: "памер" } },
  { id: "price", category: "Shopping", french: "le prix", translations: { en: "the price", be: "цана" } },
  { id: "card-payment", category: "Shopping", french: "la carte bancaire", translations: { en: "the bank card", be: "банкаўская картка" } },
  { id: "cash", category: "Shopping", french: "en espèces", translations: { en: "in cash", be: "наяўнымі" } },
  { id: "wife", category: "Daily life", french: "ma femme", translations: { en: "my wife", be: "мая жонка" } },
  { id: "friend", category: "Daily life", french: "un ami", translations: { en: "a friend", be: "сябар" } },
  { id: "message", category: "Daily life", french: "un message", translations: { en: "a message", be: "паведамленне" } },
  { id: "charger", category: "Daily life", french: "le chargeur", translations: { en: "the charger", be: "зарадная прылада" } },
  { id: "early", category: "Time", french: "tôt", translations: { en: "early", be: "рана" } },
  { id: "late", category: "Time", french: "en retard", translations: { en: "late", be: "позна" } },
  { id: "beautiful-feminine", category: "Descriptions", french: "belle", translations: { en: "beautiful", be: "прыгожая" } },
  { id: "easy", category: "Descriptions", french: "facile", translations: { en: "easy", be: "лёгкі" } },
  { id: "difficult", category: "Descriptions", french: "difficile", translations: { en: "difficult", be: "цяжкі" } },
];
