export const vocabulary = [
  { id: "hello", category: "Greetings", french: "bonjour", translations: { en: "hello", be: "прывітанне" } },
  { id: "good-evening", category: "Greetings", french: "bonsoir", translations: { en: "good evening", be: "добры вечар" } },
  { id: "goodbye", category: "Greetings", french: "au revoir", translations: { en: "goodbye", be: "да пабачэння" } },
  { id: "see-you-soon", category: "Greetings", french: "à bientôt", translations: { en: "see you soon", be: "да хуткай сустрэчы" } },
  { id: "thanks", category: "Politeness", french: "merci", translations: { en: "thank you", be: "дзякуй" } },
  { id: "please", category: "Politeness", french: "s’il te plaît", translations: { en: "please", be: "калі ласка" } },
  { id: "sorry", category: "Politeness", french: "pardon", translations: { en: "sorry", be: "прабач" } },
  { id: "yes", category: "Basics", french: "oui", translations: { en: "yes", be: "так" } },
  { id: "no", category: "Basics", french: "non", translations: { en: "no", be: "не" } },
  { id: "maybe", category: "Basics", french: "peut-être", translations: { en: "maybe", be: "магчыма" } },
  { id: "here", category: "Basics", french: "ici", translations: { en: "here", be: "тут" } },
  { id: "there", category: "Basics", french: "là-bas", translations: { en: "over there", be: "там" } },
  { id: "water", category: "Food", french: "de l’eau", translations: { en: "water", be: "вада" } },
  { id: "bread", category: "Food", french: "du pain", translations: { en: "bread", be: "хлеб" } },
  { id: "coffee", category: "Food", french: "un café", translations: { en: "a coffee", be: "кава" } },
  { id: "tea", category: "Food", french: "du thé", translations: { en: "tea", be: "гарбата" } },
  { id: "milk", category: "Food", french: "du lait", translations: { en: "milk", be: "малако" } },
  { id: "sugar", category: "Food", french: "du sucre", translations: { en: "sugar", be: "цукар" } },
  { id: "salt", category: "Food", french: "du sel", translations: { en: "salt", be: "соль" } },
  { id: "apple", category: "Food", french: "une pomme", translations: { en: "an apple", be: "яблык" } },
  { id: "banana", category: "Food", french: "une banane", translations: { en: "a banana", be: "банан" } },
  { id: "cheese", category: "Food", french: "du fromage", translations: { en: "cheese", be: "сыр" } },
  { id: "rice", category: "Food", french: "du riz", translations: { en: "rice", be: "рыс" } },
  { id: "soup", category: "Food", french: "de la soupe", translations: { en: "soup", be: "суп" } },
  { id: "chicken", category: "Food", french: "du poulet", translations: { en: "chicken", be: "курыца" } },
  { id: "fish", category: "Food", french: "du poisson", translations: { en: "fish", be: "рыба" } },
  { id: "house", category: "Home", french: "la maison", translations: { en: "the house", be: "дом" } },
  { id: "room", category: "Home", french: "la chambre", translations: { en: "the bedroom", be: "спальня" } },
  { id: "kitchen", category: "Home", french: "la cuisine", translations: { en: "the kitchen", be: "кухня" } },
  { id: "bathroom", category: "Home", french: "la salle de bain", translations: { en: "the bathroom", be: "ванны пакой" } },
  { id: "door", category: "Home", french: "la porte", translations: { en: "the door", be: "дзверы" } },
  { id: "window", category: "Home", french: "la fenêtre", translations: { en: "the window", be: "акно" } },
  { id: "table", category: "Home", french: "la table", translations: { en: "the table", be: "стол" } },
  { id: "chair", category: "Home", french: "la chaise", translations: { en: "the chair", be: "крэсла" } },
  { id: "bed", category: "Home", french: "le lit", translations: { en: "the bed", be: "ложак" } },
  { id: "key", category: "Home", french: "la clé", translations: { en: "the key", be: "ключ" } },
  { id: "phone", category: "Daily life", french: "le téléphone", translations: { en: "the phone", be: "тэлефон" } },
  { id: "bag", category: "Daily life", french: "le sac", translations: { en: "the bag", be: "сумка" } },
  { id: "book", category: "Daily life", french: "le livre", translations: { en: "the book", be: "кніга" } },
  { id: "pen", category: "Daily life", french: "le stylo", translations: { en: "the pen", be: "ручка" } },
  { id: "money", category: "Daily life", french: "l’argent", translations: { en: "money", be: "грошы" } },
  { id: "ticket", category: "Daily life", french: "le ticket", translations: { en: "the ticket", be: "білет" } },
  { id: "today", category: "Time", french: "aujourd’hui", translations: { en: "today", be: "сёння" } },
  { id: "tomorrow", category: "Time", french: "demain", translations: { en: "tomorrow", be: "заўтра" } },
  { id: "yesterday", category: "Time", french: "hier", translations: { en: "yesterday", be: "учора" } },
  { id: "morning", category: "Time", french: "le matin", translations: { en: "the morning", be: "раніца" } },
  { id: "evening", category: "Time", french: "le soir", translations: { en: "the evening", be: "вечар" } },
  { id: "now", category: "Time", french: "maintenant", translations: { en: "now", be: "зараз" } },
  { id: "later", category: "Time", french: "plus tard", translations: { en: "later", be: "пазней" } },
  { id: "monday", category: "Time", french: "lundi", translations: { en: "Monday", be: "панядзелак" } },
  { id: "friday", category: "Time", french: "vendredi", translations: { en: "Friday", be: "пятніца" } },
  { id: "happy", category: "Feelings", french: "content", translations: { en: "happy", be: "рады" } },
  { id: "tired", category: "Feelings", french: "fatiguée", translations: { en: "tired", be: "стомленая" } },
  { id: "hungry", category: "Feelings", french: "j’ai faim", translations: { en: "I am hungry", be: "я галодная" } },
  { id: "thirsty", category: "Feelings", french: "j’ai soif", translations: { en: "I am thirsty", be: "я хачу піць" } },
  { id: "cold", category: "Feelings", french: "j’ai froid", translations: { en: "I am cold", be: "мне холадна" } },
  { id: "hot", category: "Feelings", french: "j’ai chaud", translations: { en: "I am hot", be: "мне горача" } },
  { id: "sick", category: "Health", french: "malade", translations: { en: "sick", be: "хворая" } },
  { id: "head", category: "Health", french: "la tête", translations: { en: "the head", be: "галава" } },
  { id: "stomach", category: "Health", french: "le ventre", translations: { en: "the stomach", be: "жывот" } },
  { id: "medicine", category: "Health", french: "le médicament", translations: { en: "the medicine", be: "лекі" } },
  { id: "doctor", category: "Health", french: "le médecin", translations: { en: "the doctor", be: "доктар" } },
  { id: "street", category: "Places", french: "la rue", translations: { en: "the street", be: "вуліца" } },
  { id: "shop", category: "Places", french: "le magasin", translations: { en: "the shop", be: "крама" } },
  { id: "restaurant", category: "Places", french: "le restaurant", translations: { en: "the restaurant", be: "рэстаран" } },
  { id: "station", category: "Places", french: "la gare", translations: { en: "the train station", be: "вакзал" } },
  { id: "pharmacy", category: "Places", french: "la pharmacie", translations: { en: "the pharmacy", be: "аптэка" } },
  { id: "park", category: "Places", french: "le parc", translations: { en: "the park", be: "парк" } },
  { id: "car", category: "Transport", french: "la voiture", translations: { en: "the car", be: "машына" } },
  { id: "train", category: "Transport", french: "le train", translations: { en: "the train", be: "цягнік" } },
  { id: "bus", category: "Transport", french: "le bus", translations: { en: "the bus", be: "аўтобус" } },
  { id: "metro", category: "Transport", french: "le métro", translations: { en: "the metro", be: "метро" } },
  { id: "left", category: "Directions", french: "à gauche", translations: { en: "to the left", be: "налева" } },
  { id: "right", category: "Directions", french: "à droite", translations: { en: "to the right", be: "направа" } },
  { id: "straight", category: "Directions", french: "tout droit", translations: { en: "straight ahead", be: "прама" } },
  { id: "near", category: "Directions", french: "près de", translations: { en: "near", be: "каля" } },
  { id: "far", category: "Directions", french: "loin de", translations: { en: "far from", be: "далёка ад" } },
  { id: "small", category: "Descriptions", french: "petit", translations: { en: "small", be: "маленькі" } },
  { id: "big", category: "Descriptions", french: "grand", translations: { en: "big", be: "вялікі" } },
  { id: "good", category: "Descriptions", french: "bon", translations: { en: "good", be: "добры" } },
  { id: "beautiful", category: "Descriptions", french: "beau", translations: { en: "beautiful", be: "прыгожы" } },
  { id: "expensive", category: "Shopping", french: "cher", translations: { en: "expensive", be: "дарагі" } },
  { id: "cheap", category: "Shopping", french: "pas cher", translations: { en: "cheap", be: "танны" } },
  { id: "receipt", category: "Shopping", french: "le ticket de caisse", translations: { en: "the receipt", be: "чэк" } },
];
